DROP TABLE IF EXISTS Note CASCADE;
DROP TABLE IF EXISTS Parametres CASCADE;
DROP TABLE IF EXISTS Candidat CASCADE;
DROP TABLE IF EXISTS Correcteur CASCADE;
DROP TABLE IF EXISTS Matiere CASCADE;
DROP TABLE IF EXISTS Resolution CASCADE;
DROP TABLE IF EXISTS Operateur CASCADE;

TRUNCATE TABLE Note RESTART IDENTITY CASCADE;
TRUNCATE TABLE Parametres RESTART IDENTITY CASCADE;
TRUNCATE TABLE Candidat RESTART IDENTITY CASCADE;
TRUNCATE TABLE Correcteur RESTART IDENTITY CASCADE;
TRUNCATE TABLE Matiere RESTART IDENTITY CASCADE;
TRUNCATE TABLE Resolution RESTART IDENTITY CASCADE;
TRUNCATE TABLE Operateur RESTART IDENTITY CASCADE;